### ISSUE TITLE
AAs with multiple values of Polarity in CTD calculation

### ISSUE THREAD

**Issue by Caiofcas** [MartinThoma/propy3#5]
In `CTD.py` , when the groups of the amino acids are being defined by their properties, we have :
```
_Polarity = {"1": "LIFWCMVY", "2": "CPNVEQIL", "3": "KMHFRYW"}
# '1'stand for (4.9-6.2); '2'stand for (8.0-9.2), '3' stand for (10.4-13.0)

```

Amino Acids 'V', 'M', 'L', etc have two different values.

**Comment by MartinThoma** [comment]
Sorry for responding so late. I'm a professional Python developer, but I have absolutely no knowledge of proteins. Could you tell me exactly where the issue is / how it should be?

**Comment by KimHe** [comment]
_Polarity = {"1": "LIFWCMVY", "2": "PATGS", "3": "HQRKNED"}

Well, It should be like this

**Comment by KimHe** [comment]
also error in the _NormalizedVDWV  set

_NormalizedVDWV = {"1": "GASTPDC", "2": ......}

Amino Acid "C" is missing in the key "1" values
Please check that

**Comment by jowch** [comment]
I believe @KimHe is correct on these. My lab has been using Python 2 ProPy with these corrections.

**Comment by MartinThoma** [comment]
Thank you @Caiofcas for reporting the issue! Thank you @KimHe for proposing a fix! And @jowch for confirming it! :hugs: 

Sorry it took me that long. I was switching jobs/moving apartments and generally involved in other projects. Just pinging me once in a while helps :sweat_smile:

**Comment by MartinThoma** [comment]
I've released a new version on PyPI + mentioned your contribution in the changelog: https://github.com/MartinThoma/propy3/blob/master/CHANGELOG.md - thank you!
