### ISSUE TITLE
Mutability.json input error

### ISSUE THREAD

**Issue by KimHe** [MartinThoma/propy3#7]
the value of key ("K") is 56, rather than -56

**Comment by MartinThoma** [comment]
I've only ported the code. I have no idea of the topic. Could you please give me a reference (a book / an article) where this is documented?

**Comment by KimHe** [comment]
cf. https://www.genome.jp/entry/aaindex:DAYM780201
a.k.a. AAIndex, where I'v got data from

**Comment by MartinThoma** [comment]
Thank you very much! The fix was added and a new package version uploaded.
